spring:
  application:
    name: ms-transaction

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY:test}
        secret-key: ${AWS_SECRET_KEY:test}
      region:
        static: ${AWS_REGION:us-east-1}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

http:
  client:
    authorizer:
      url: https://util.devi.tools
      path: /api/v2

async:
  queue:
    transaction:
      name: ${SQS_TRANSACTION_PROCESS_QUEUE:MQ.TRANSACTION.PROCESS}
    extract:
      name: ${SQS_EXTRACT_GENERATE_QUEUE:MQ.EXTRACT.GENERATE}

server:
  servlet:
    context-path: /ms-transaction
  port: 8080
  address: ${SERVER_ADDRESS:0.0.0.0}

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  show-actuator: true