spring:
  application:
    name: ms-authentication
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY:test}
        secret-key: ${AWS_SECRET_KEY:test}
      region:
        static: ${AWS_REGION:us-east-1}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /ms-authentication
  port: 8080

email:
  from: ${BANK_NO_REPLY_EMAIL}
