spring:
  application:
    name: app

  config:
    activate:
      on-profile: LOCAL

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/localstack

rest:
  api:
    keycloak:
      realm: localstack
      base-url: http://localhost:8080
      client-id: localstack-client
      client-secret: localstack-client-secret


server:
  port: 9090