services:
#  app:
#    build:
#        context: .
#        dockerfile: Dockerfile
#    ports:
#      - "9091:9090"
#    environment:
#      JAVA_TOOL_OPTIONS: "-Dserver.port=9090 -Dserver.address=0.0.0.0"
  mailhog:
    image: mailhog/mailhog
    restart: always
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025