name: Develop CI/CD

on:
  push:
    branches:
      - development

permissions:
  contents: read
  id-token: write

jobs:
  ci-cd:
    name: CI/CD Pipeline
    uses: ./.github/workflows/ci-cd.yml
    secrets: inherit
    with:
      environment: development